services:
  frontend:
    build: https://github.com/NebularStore/nebular-store-frontend.git
    ports:
      - 8080:5173
    env_file:
      - client.env

  backend:
    build: https://github.com/NebularStore/nebular-store-backend.git
    ports:
      - 8000:8080
    volumes:
      - ./data:/build/data/
